### ISSUE TITLE
More granular user management scopes

### ISSUE THREAD

**Issue by mike-marcacci** [the-control-group/authx#2]
Right now user management is more or less all-or-nothing. This is probably not ideal in an organization with any hierarchy. Our options include:
### 1. Restrict by "team"

`AuthX:user.<team_id>:**`
Teams are really a half-baked feature right now and I'm hesitant to depend on them too much for core functionality. Additionally, right now a user can change his/her team without any special permissions (this was one of the goals of the team model). We could, however, update their meaning and give the ability to change one's team its own scope.

The problem here is with hidden loopholes: someone may be able to reset the password of (or otherwise impersonate) a team member who has higher levels of access, thereby gaining access herself. Because teams do NOT correspond directly to roles (which are necessarily flat), a moderately complex organization could quickly begin exposing itself to vulnerability as teams and roles evolve.
### 2. Restrict by "scopes"

`AuthX:user.<superior | peer | subordinate>:**`
Because AuthX is aware of every user's scopes, it can trivially compare the abilities of one user to another. Instead of shifting the complexity to the users, who would under option 1 need to design their roles/teams accordingly, we could divide the users by relationship: superior, peer, subordinate. This way, if a user is given specific (perhaps initially temporary) access to a scope, her supervisors are not inadvertently also given such access.

**Comment by mike-marcacci** [comment]
I've added a `relationshipTo` method to the User model in 3d90c2e7fadc274803d1578bb5d929e5907997b4 which performs the comparison, returning one of:

- self
- peer
- superior
- subordinate
- mixed

I propose replacing `AuthX:me:**` with `AuthX:user.self:**` from here on out.

**Comment by ChrisMcKenzie** [comment]
I am going to bring the guys that are using authx right now as this will break there apps if change unknowingly. 

**cc:** @mattwarren1234 @jfurfaro @dlabey @ericgreene

**Comment by jfurfaro** [comment]
Works for me - I only query by role (TCG employee) at the moment and can update any requests to /v1/me when changes get pushed
