### ISSUE TITLE
SCIM Support in AuthX

### ISSUE THREAD

**Issue by PasiPraveen** [the-control-group/authx#542]
Hi,
We are planning to use AuthX as an identity Server that has SCIM API's exposed.
Our primary goal is to invoke SCIM API's exposed by AuthX and perform user/group related operations.
Can you please let us know if AuthX has SCIM support and exposes SCIM API's that can be consumed by us.

Regards,
Praveen

**Comment by mike-marcacci** [comment]
Hi @PasiPraveen,

We currently do _not_ support SCIM in either direction as a direct part of the open source AuthX. Internally we actually _do_ use SCIM and have additional functionality built on top of the open source AuthX. However, this wasn't designed to be externalized and does make a number of assumptions about our particular setup.

This is something we would definitely be interested in implementing generically (ideally working with external collaborators such as yourself) and we already have the following open feature requests:
- https://github.com/the-control-group/authx/issues/53
- https://github.com/the-control-group/authx/issues/51

It sounds like you're interested in both of these?

**Comment by mike-marcacci** [comment]
Closing this, as it's likely already covered by the linked issues.
