### ISSUE TITLE
Add SAML strategy

### ISSUE THREAD

**Issue by mike-marcacci** [the-control-group/authx#57]
We already have a need for a SAML authorization strategy. For our particular case, these credentials will need to be created by the SCIM provisioner, so this feature should help inform design decisions for #56.

**Comment by mike-marcacci** [comment]
I had thought that we could avoid doing this immediately, since OneLogin now supports OpenID Connect... but it appears that their "SCIM apps" are still required to use SAML. This has bumped up on the priority list.

**Comment by ebrown32** [comment]
The SAML strategy has been added.
